/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketmanager;

import static basketmanager.TestMain.filePath;
import database.DatabaseManager;
import database.FileDatabaseManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import objects.PlayerRecord;
import tools.GlobalVariables;

/**
 *
 * @author
 */
public class BasketManagerJFrame extends javax.swing.JFrame {

//    ExcelManagerInterface excelManager;
//    PlayerManagerInterface playerManager;
    /**
     * Creates new form BasketManagerJFrame
     */
    public BasketManagerJFrame() {
        initComponents();

//        excelManager = new ExcelManager();
        initApp();

        clearMainBodyContent();
    }

    private void initApp() {
        initPlayersStoreFile();

        initMatchesStoreFile();

        initGamesStoreFile();
    }

    private void initPlayersStoreFile() {
        File playersRaf = new File(GlobalVariables.pathPlayersRaf);
        if (!playersRaf.exists()) {
            DatabaseManager.createRafStoreFile(GlobalVariables.pathPlayersRaf);
        }
    }

    private void initMatchesStoreFile() {
        File playersRaf = new File(GlobalVariables.pathMatchesRaf);

        if (!playersRaf.exists()) {
            DatabaseManager.createRafStoreFile(GlobalVariables.pathMatchesRaf);
        }
    }

    private void initGamesStoreFile() {
        File playersRaf = new File(GlobalVariables.pathGamesRaf);

        if (!playersRaf.exists()) {
            DatabaseManager.createRafStoreFile(GlobalVariables.pathGamesRaf);
        }
    }

    private void changeMainBodyContent(JPanel newJPanel) {
        clearMainBodyContent();

        jPanel_MainBody.add(newJPanel, BorderLayout.PAGE_START);

        jPanel_MainBody.revalidate();
        jPanel_MainBody.repaint();
    }

    private void clearMainBodyContent() {
        jPanel_MainBody.removeAll();
        jPanel_MainBody.revalidate();
        jPanel_MainBody.repaint();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AddMatchData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Opponent = new javax.swing.JTextField();
        jTextField_FoulsCommited = new javax.swing.JTextField();
        jTextField_FoulsConceded = new javax.swing.JTextField();
        jTextField_Assists = new javax.swing.JTextField();
        jTextField_Rebounds = new javax.swing.JTextField();
        jTextField_Steals = new javax.swing.JTextField();
        jTextField_Blocks = new javax.swing.JTextField();
        jTextField_PointsScored = new javax.swing.JTextField();
        jTextField_PointsConceded = new javax.swing.JTextField();
        jTextField_Location = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton_NewMatchAdd = new javax.swing.JButton();
        jPanel_PlayerAdd = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_PlayerFirstName = new javax.swing.JTextField();
        jTextField_PlayerLastName = new javax.swing.JTextField();
        jTextField_PlayerDoB = new javax.swing.JTextField();
        jTextField_PlayerPoB = new javax.swing.JTextField();
        jTextField_PlayerHeight = new javax.swing.JTextField();
        jTextField_PlayerWeight = new javax.swing.JTextField();
        jTextField_PlayerPosition = new javax.swing.JTextField();
        jTextField_PlayerJersey = new javax.swing.JTextField();
        jButton_PlayerAdd = new javax.swing.JButton();
        jLabel_PlayerAddMessage = new javax.swing.JLabel();
        jPanel_PlayerList = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_PlayersList = new javax.swing.JTable();
        jPanel_PlayerAddGame = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField_PlayerGameFoulsCommitted = new javax.swing.JTextField();
        jTextField_PlayerGameFoulsConceded = new javax.swing.JTextField();
        jTextField_PlayerGameAssists = new javax.swing.JTextField();
        jTextField_PlayerGameRebounds = new javax.swing.JTextField();
        jTextField_PlayerGameSteals = new javax.swing.JTextField();
        jTextField_PlayerGameBlocks = new javax.swing.JTextField();
        jTextField_PlayerGameAwayTeamName = new javax.swing.JTextField();
        jTextField_PlayerGamePointsScored = new javax.swing.JTextField();
        jButton_PlayerAddGame = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField_PlayerGameLocation = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox_PlayerGameHomeGame = new javax.swing.JCheckBox();
        jPanel_Main = new javax.swing.JPanel();
        jPanel_MainBody = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_FileExit = new javax.swing.JMenuItem();
        jMenu_Season = new javax.swing.JMenu();
        jMenuItem_SeasonAddSeason = new javax.swing.JMenuItem();
        jMenuItem_SeasonList = new javax.swing.JMenuItem();
        jMenu_Player = new javax.swing.JMenu();
        jMenuItem_PlayerAdd = new javax.swing.JMenuItem();
        jMenuItem_PlayerList = new javax.swing.JMenuItem();
        jMenu_MatchData = new javax.swing.JMenu();
        jMenuItem_MatchAddNew = new javax.swing.JMenuItem();
        jMenu_Statictis = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jPanel_AddMatchData.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Match Data"));

        jLabel2.setText("Opponent");

        jLabel3.setText("Date");

        jLabel4.setText("Fouls Commited");

        jLabel5.setText("Fouls Conceded");

        jLabel6.setText("Assists");

        jLabel7.setText("Rebounds");

        jLabel8.setText("Steals");

        jLabel9.setText("Blocks");

        jLabel13.setText("Points Scored");

        jLabel14.setText("Points Conceded");

        jLabel15.setText("Location (City/Town)");

        jCheckBox1.setText("Home Game");

        jButton_NewMatchAdd.setText("Add");

        javax.swing.GroupLayout jPanel_AddMatchDataLayout = new javax.swing.GroupLayout(jPanel_AddMatchData);
        jPanel_AddMatchData.setLayout(jPanel_AddMatchDataLayout);
        jPanel_AddMatchDataLayout.setHorizontalGroup(
            jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AddMatchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AddMatchDataLayout.createSequentialGroup()
                        .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Opponent)
                            .addComponent(jTextField_FoulsCommited)
                            .addComponent(jTextField_FoulsConceded)
                            .addComponent(jTextField_Assists)
                            .addComponent(jTextField_Rebounds)
                            .addComponent(jTextField_Steals)
                            .addComponent(jTextField_Blocks)
                            .addComponent(jTextField_PointsScored)
                            .addComponent(jTextField_PointsConceded)
                            .addComponent(jTextField_Location)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(jButton_NewMatchAdd))
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanel_AddMatchDataLayout.setVerticalGroup(
            jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AddMatchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Opponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_FoulsCommited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_FoulsConceded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Assists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Rebounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Steals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Blocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_PointsScored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_PointsConceded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AddMatchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton_NewMatchAdd)
                .addContainerGap())
        );

        jPanel_PlayerAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Player"));
        jPanel_PlayerAdd.setPreferredSize(new java.awt.Dimension(970, 570));
        jPanel_PlayerAdd.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("First Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel10.setText("Last Name");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel11.setText("DoB");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel12.setText("PoB");
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel16.setText("Height");
        jLabel16.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel17.setText("Weight");
        jLabel17.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel18.setText("Position");
        jLabel18.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel19.setText("Jersey");
        jLabel19.setPreferredSize(new java.awt.Dimension(150, 16));

        jTextField_PlayerFirstName.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerLastName.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerDoB.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerPoB.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerHeight.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerWeight.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerPosition.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerJersey.setPreferredSize(new java.awt.Dimension(200, 28));

        jButton_PlayerAdd.setText("Add");
        jButton_PlayerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayerAddActionPerformed(evt);
            }
        });

        jLabel_PlayerAddMessage.setForeground(java.awt.Color.red);
        jLabel_PlayerAddMessage.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_PlayerAddMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerPoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_PlayerJersey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_PlayerAdd))
                        .addGap(0, 584, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerPoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerJersey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_PlayerAddMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jButton_PlayerAdd)
                .addContainerGap())
        );

        jPanel_PlayerAdd.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel_PlayerList.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Players"));
        jPanel_PlayerList.setLayout(new java.awt.BorderLayout());

        jTable_PlayersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "First Name", "Last Name", "DoB", "PoB", "Height", "Weight", "Position", "Jersey"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_PlayersList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_PlayerList.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel_PlayerAddGame.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Game"));
        jPanel_PlayerAddGame.setPreferredSize(new java.awt.Dimension(970, 570));
        jPanel_PlayerAddGame.setLayout(new java.awt.BorderLayout());

        jLabel20.setText("Fouls Committed");
        jLabel20.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel21.setText("Fouls Conceded");
        jLabel21.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel22.setText("Assists");
        jLabel22.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel23.setText("Rebounds");
        jLabel23.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel24.setText("Steals");
        jLabel24.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel25.setText("Blocks");
        jLabel25.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel26.setText("Away Team");
        jLabel26.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel27.setText("Points Scored");
        jLabel27.setPreferredSize(new java.awt.Dimension(150, 16));

        jTextField_PlayerGameFoulsCommitted.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameFoulsConceded.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameAssists.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameRebounds.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameSteals.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameBlocks.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGameAwayTeamName.setPreferredSize(new java.awt.Dimension(200, 28));

        jTextField_PlayerGamePointsScored.setPreferredSize(new java.awt.Dimension(200, 28));

        jButton_PlayerAddGame.setText("Add");
        jButton_PlayerAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayerAddGameActionPerformed(evt);
            }
        });

        jLabel28.setText("Location/City");
        jLabel28.setPreferredSize(new java.awt.Dimension(150, 16));

        jTextField_PlayerGameLocation.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel29.setText("Game Date");
        jLabel29.setPreferredSize(new java.awt.Dimension(150, 16));

        jCheckBox_PlayerGameHomeGame.setText("Home Game");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameFoulsCommitted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameFoulsConceded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameAssists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameRebounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameSteals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameAwayTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGamePointsScored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_PlayerAddGame)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PlayerGameLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_PlayerGameHomeGame)
                            .addComponent(jTextField_PlayerGameBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameFoulsCommitted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameFoulsConceded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameAssists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameRebounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameSteals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_PlayerGameHomeGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameAwayTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGamePointsScored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PlayerGameLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton_PlayerAddGame)
                .addContainerGap())
        );

        jPanel_PlayerAddGame.add(jPanel3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel_MainBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_MainBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_MainBody, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_MainBody, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu_File.setText("File");

        jMenuItem_FileExit.setText("Exit");
        jMenuItem_FileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FileExitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_FileExit);

        jMenuBar1.add(jMenu_File);

        jMenu_Season.setText("Season");

        jMenuItem_SeasonAddSeason.setText("Add New");
        jMenuItem_SeasonAddSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SeasonAddSeasonActionPerformed(evt);
            }
        });
        jMenu_Season.add(jMenuItem_SeasonAddSeason);

        jMenuItem_SeasonList.setText("Seasons List");
        jMenuItem_SeasonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SeasonListActionPerformed(evt);
            }
        });
        jMenu_Season.add(jMenuItem_SeasonList);

        jMenuBar1.add(jMenu_Season);

        jMenu_Player.setText("Player");

        jMenuItem_PlayerAdd.setText("Add Player");
        jMenuItem_PlayerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PlayerAddActionPerformed(evt);
            }
        });
        jMenu_Player.add(jMenuItem_PlayerAdd);

        jMenuItem_PlayerList.setText("Player List");
        jMenuItem_PlayerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PlayerListActionPerformed(evt);
            }
        });
        jMenu_Player.add(jMenuItem_PlayerList);

        jMenuBar1.add(jMenu_Player);

        jMenu_MatchData.setText("Match Data");

        jMenuItem_MatchAddNew.setText("Add New Match");
        jMenuItem_MatchAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MatchAddNewActionPerformed(evt);
            }
        });
        jMenu_MatchData.add(jMenuItem_MatchAddNew);

        jMenuBar1.add(jMenu_MatchData);

        jMenu_Statictis.setText("Statistics");

        jMenuItem1.setText("Single Season");
        jMenu_Statictis.add(jMenuItem1);

        jMenuItem2.setText("Multiple Seasons");
        jMenu_Statictis.add(jMenuItem2);

        jMenuBar1.add(jMenu_Statictis);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_FileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuItem_FileExitActionPerformed

    private void jMenuItem_SeasonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SeasonListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_SeasonListActionPerformed

    private void jMenuItem_SeasonAddSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SeasonAddSeasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_SeasonAddSeasonActionPerformed

    private void jMenuItem_MatchAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MatchAddNewActionPerformed
        changeMainBodyContent(jPanel_AddMatchData);
    }//GEN-LAST:event_jMenuItem_MatchAddNewActionPerformed

    private void jMenuItem_PlayerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PlayerAddActionPerformed
        changeMainBodyContent(jPanel_PlayerAdd);
    }//GEN-LAST:event_jMenuItem_PlayerAddActionPerformed

    private void jButton_PlayerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayerAddActionPerformed
        String FirstName = jTextField_PlayerFirstName.getText().trim();
        String LastName = jTextField_PlayerLastName.getText().trim();
        String DoB = jTextField_PlayerDoB.getText().trim();
        String PoB = jTextField_PlayerPoB.getText().trim();
        String Height = jTextField_PlayerHeight.getText().trim();
        String Weight = jTextField_PlayerWeight.getText().trim();
        String Position = jTextField_PlayerPosition.getText().trim();
        String Jersey = jTextField_PlayerJersey.getText().trim();

        if (!FirstName.equals("") && !LastName.equals("") && !DoB.equals("") 
                && !PoB.equals("") && !Height.equals("") && !Weight.equals("") 
                && !Position.equals("") && !Jersey.equals("")) {
            
            PlayerRecord playerRecord = new PlayerRecord();
            FileDatabaseManager database;
            try {
                database = new FileDatabaseManager(GlobalVariables.pathPlayersRaf, playerRecord);
                PlayerRecord newPlayerRecord = new PlayerRecord(DatabaseManager.generateNewPlayerEntryId(GlobalVariables.pathPlayersRaf), FirstName, LastName, DoB, PoB, Height, Weight, Position, Jersey);
                database.insertRecord(newPlayerRecord);
            } catch (IOException ex) {
                Logger.getLogger(BasketManagerJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jLabel_PlayerAddMessage.setText("Player added successfully");
            jLabel_PlayerAddMessage.setForeground(Color.BLUE);
        } else {
            jLabel_PlayerAddMessage.setText("All fields should be filled!");
            jLabel_PlayerAddMessage.setForeground(Color.RED);
        }

        clearAddNewPlayer();
    }//GEN-LAST:event_jButton_PlayerAddActionPerformed

    private void jButton_PlayerAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayerAddGameActionPerformed

    }//GEN-LAST:event_jButton_PlayerAddGameActionPerformed

    private void jMenuItem_PlayerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PlayerListActionPerformed

        try {
            ArrayList<PlayerRecord> allPlayers = DatabaseManager.getAllPlayerEntries(GlobalVariables.pathPlayersRaf);

            DefaultTableModel tableModel = (DefaultTableModel) jTable_PlayersList.getModel();
            tableModel.setRowCount(0); // Clear table model

            for (PlayerRecord player : allPlayers) {
                Object[] tmpPlayerRow = new Object[]{
                    player.getId(),
                    player.getFirstName().trim(),
                    player.getLastName().trim(),
                    player.getDoB().trim(),
                    player.getPoB().trim(),
                    player.getHeight().trim(),
                    player.getWeight().trim(),
                    player.getPosition().trim(),
                    player.getJersey().trim()
                };

                tableModel.addRow(tmpPlayerRow);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(BasketManagerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        changeMainBodyContent(jPanel_PlayerList);
    }//GEN-LAST:event_jMenuItem_PlayerListActionPerformed

    private void clearAddNewPlayer() {
        jTextField_PlayerFirstName.setText("");
        jTextField_PlayerLastName.setText("");
        jTextField_PlayerDoB.setText("");
        jTextField_PlayerPoB.setText("");
        jTextField_PlayerHeight.setText("");
        jTextField_PlayerWeight.setText("");
        jTextField_PlayerPosition.setText("");
        jTextField_PlayerJersey.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasketManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasketManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasketManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasketManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasketManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NewMatchAdd;
    private javax.swing.JButton jButton_PlayerAdd;
    private javax.swing.JButton jButton_PlayerAddGame;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox_PlayerGameHomeGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_PlayerAddMessage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_FileExit;
    private javax.swing.JMenuItem jMenuItem_MatchAddNew;
    private javax.swing.JMenuItem jMenuItem_PlayerAdd;
    private javax.swing.JMenuItem jMenuItem_PlayerList;
    private javax.swing.JMenuItem jMenuItem_SeasonAddSeason;
    private javax.swing.JMenuItem jMenuItem_SeasonList;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_MatchData;
    private javax.swing.JMenu jMenu_Player;
    private javax.swing.JMenu jMenu_Season;
    private javax.swing.JMenu jMenu_Statictis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_AddMatchData;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_MainBody;
    private javax.swing.JPanel jPanel_PlayerAdd;
    private javax.swing.JPanel jPanel_PlayerAddGame;
    private javax.swing.JPanel jPanel_PlayerList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_PlayersList;
    private javax.swing.JTextField jTextField_Assists;
    private javax.swing.JTextField jTextField_Blocks;
    private javax.swing.JTextField jTextField_FoulsCommited;
    private javax.swing.JTextField jTextField_FoulsConceded;
    private javax.swing.JTextField jTextField_Location;
    private javax.swing.JTextField jTextField_Opponent;
    private javax.swing.JTextField jTextField_PlayerDoB;
    private javax.swing.JTextField jTextField_PlayerFirstName;
    private javax.swing.JTextField jTextField_PlayerGameAssists;
    private javax.swing.JTextField jTextField_PlayerGameAwayTeamName;
    private javax.swing.JTextField jTextField_PlayerGameBlocks;
    private javax.swing.JTextField jTextField_PlayerGameFoulsCommitted;
    private javax.swing.JTextField jTextField_PlayerGameFoulsConceded;
    private javax.swing.JTextField jTextField_PlayerGameLocation;
    private javax.swing.JTextField jTextField_PlayerGamePointsScored;
    private javax.swing.JTextField jTextField_PlayerGameRebounds;
    private javax.swing.JTextField jTextField_PlayerGameSteals;
    private javax.swing.JTextField jTextField_PlayerHeight;
    private javax.swing.JTextField jTextField_PlayerJersey;
    private javax.swing.JTextField jTextField_PlayerLastName;
    private javax.swing.JTextField jTextField_PlayerPoB;
    private javax.swing.JTextField jTextField_PlayerPosition;
    private javax.swing.JTextField jTextField_PlayerWeight;
    private javax.swing.JTextField jTextField_PointsConceded;
    private javax.swing.JTextField jTextField_PointsScored;
    private javax.swing.JTextField jTextField_Rebounds;
    private javax.swing.JTextField jTextField_Steals;
    // End of variables declaration//GEN-END:variables
}
